name: gRPC-js Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.workspace }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g typescript
    - run: |
        cd ${{ github.workspace }}/packages/proto-loader/
        npm install
    - run: |
        cd ${{ github.workspace }}/grpc-js/
        npm install
    - run: npm run test
